Update permission-db.yml

diff --git a/.github/workflows/permission-db.yml b/.github/workflows/permission-db.yml
--- a/.github/workflows/permission-db.yml
+++ b/.github/workflows/permission-db.yml
@@ -13,6 +13,18 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+
+      - name: Check Branch, Trigger and PR Author
+        run: |
+          # Sadece belirli kullanıcıların açtığı PR'lar
+          PR_USER="${{ github.event.pull_request.user.login }}"
+
+          if [ "$PR_USER" != "mysoly" ] && [ "$PR_USER" != "msklc" ]; then
+            echo "This PR was opened by '$PR_USER'. Only 'msklc' and 'bayyavuz' are allowed. Failing..."
+            exit 1
+          fi
+
+          echo "This is a pull request from staging to main and opened by an allowed user. Performing required steps..."
       - name: Install psql and jq
         run: |
           sudo apt-get update
